language: java

jdk:
- oraclejdk8

addons:
  postgresql: "9.5"

services:
  - postgresql
before_script:
    - psql -c "CREATE DATABASE sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;" -U postgres
    - psql -c "CREATE DATABASE testdatabase ENCODING = 'UTF8' CONNECTION LIMIT = -1;" -U postgres
    - psql -c "CREATE USER sqlcmd WITH PASSWORD 'sqlcmd' SUPERUSER CREATEDB CREATEROLE VALID UNTIL 'infinity';" -U
     postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE sqlcmd TO sqlcmd;" -U postgres
    - psql -c "GRANT ALL PRIVILEGES ON DATABASE testdatabase TO sqlcmd;" -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE sqlcmd TO public;" -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE testdatabase TO public;" -U postgres

cache:
 directories:
   - $HOME/.m2
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
