language: java
services:
  - postgresql
addons:
  postgresql: "9.4"
before_script:
    - psql -c "CREATE DATABASE sqlcmd;" -U postgres
    - psql -c "CREATE DATABASE testdatabase;" -U postgres
    - psql -c "CREATE ROLE sqlcmd WITH PASSWORD 'sqlcmd' LOGIN
                 SUPERUSER CREATEDB CREATEROLE
                  VALID UNTIL 'infinity';" -U postgres
    - psql -c "GRANT SELECT, UPDATE, INSERT ON ALL TABLES IN SCHEMA public TO sqlcmd;" -U postgres

test:
  adapter: postgresql
  database: sqlcmd
