language: java
sudo: required
jdk:
- oraclejdk8

addons:
  postgresql: "9.5"

services:
  - postgresql
before_script:
#    - sudo vim /etc/postgresql/9.5/main/pg_hba.conf
    - psql -c "CREATE USER sqlcmd WITH PASSWORD 'sqlcmd' CREATEDB CREATEROLE;" -U postgres
    - psql -c "CREATE DATABASE sqlcmd OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;" -U postgres
    - psql -c "CREATE DATABASE testdatabase OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;" -U postgres
    - psql -c "GRANT ALL ON DATABASE sqlcmd TO sqlcmd;" -U postgres
    - psql -c "GRANT ALL ON DATABASE testdatabase TO sqlcmd;" -U postgres
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" sqlcmd -U postgres
    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d sqlcmd -U postgres
    - psql -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d sqlcmd -U postgres
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" -d testdatabase -U postgres
    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d testdatabase -U postgres
    - psql -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d testdatabase -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE sqlcmd TO public;" -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE testdatabase TO public;" -U postgres
    - psql -c "select * from pg_namespace;" -U postgres

cache:
 directories:
   - $HOME/.m2
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
