language: java
sudo: required
jdk:
- oraclejdk8

addons:
  postgresql: "9.6"

services:
  - postgresql
before_script:
#    - sudo vim /etc/postgresql/9.5/main/pg_hba.conf
    - psql -U postgres -c "CREATE USER sqlcmd PASSWORD 'sqlcmd' CREATEDB CREATEROLE;"
    - psql -U postgres -c "CREATE DATABASE sqlcmd OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;"
    - psql -U postgres -c "CREATE DATABASE sqlcmd_test OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;"
    - sudo sed -i 's/local   all             all                                     trust/local   all             sqlcmd                                     md5/g' /etc/postgresql/9.6/main/pg_hba.conf
    - sudo sed -i 's/local   all             all                                     trust/local   all             sqlcmd_test                                     md5/g' /etc/postgresql/9.6/main/pg_hba.conf
    - sudo sed -i 's/host    all             all             127.0.0.1\/32            trust/host    all             sqlcmd             127.0.0.1\/32            md5/g' /etc/postgresql/9.6/main/pg_hba.conf
    - sudo sed -i 's/host    all             all             127.0.0.1\/32            trust/host    all             sqlcmd_test             127.0.0.1\/32            md5/g' /etc/postgresql/9.6/main/pg_hba.conf
    - sudo sed -i 's/host    all             all             ::1\/128                 trust/host    all             sqlcmd             ::1\/128                 md5/g' /etc/postgresql/9.6/main/pg_hba.conf
    - sudo sed -i 's/host    all             all             ::1\/128                 trust/host    all             sqlcmd_test             ::1\/128                 md5/g' /etc/postgresql/9.6/main/pg_hba.conf
    - sudo service postgresql restart
    - sudo cat /etc/postgresql/9.6/main/pg_hba.conf

#    - psql -U postgres -c "GRANT ALL ON DATABASE sqlcmd TO sqlcmd;"
#    - psql -U postgres -c "GRANT ALL ON DATABASE testdatabase TO sqlcmd;"
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" sqlcmd -U postgres
#    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d sqlcmd -U postgres
#    - psql -U postgres -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d sqlcmd
#    - psql -U postgres -c "GRANT ALL ON SCHEMA public TO sqlcmd;" -d sqlcmd
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" -d sqlcmd_test -U postgres
#    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d sqlcmd_test -U postgres
#    - psql -U postgres -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d sqlcmd_test
#    - psql -U postgres -c "GRANT ALL ON SCHEMA public TO sqlcmd;" -d sqlcmd_test
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE sqlcmd TO public;" -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE testdatabase TO public;" -U postgres
#    - psql -U sqlcmd -c "CREATE TABLE table1 (title varchar(40) NOT NULL);" -d sqlcmd
#    - psql -U sqlcmd -c "CREATE TABLE table1 (title varchar(40) NOT NULL);" -d testdatabase
#    - psql -U postgres -c "select * from pg_namespace;"
#    - psql -U postgres -c "SELECT datname FROM pg_database WHERE datistemplate = false;"
#    - psql -U sqlcmd -c "select * from pg_stat_user_tables;" -d sqlcmd -p 'sqlcmd'
#    - psql -U sqlcmd -c "select * from pg_stat_user_tables;" -d sqlcmd_test -p 'sqlcmd'
#    - psql -U sqlcmd -c " DROP DATABASE testdatabase;" -d sqlcmd

cache:
 directories:
   - $HOME/.m2
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
