language: java

jdk:
- oraclejdk8

addons:
  postgresql: "9.6"

services:
  - postgresql

before_script:
    - sudo mv -f $TRAVIS_BUILD_DIR/target/test-classes/config/pg_hba.conf /etc/postgresql/9.6/main/
    - sudo service postgresql restart
    - psql -U postgres -c "CREATE USER sqlcmd PASSWORD 'sqlcmd';"
    - psql -U postgres -c "CREATE DATABASE sqlcmd OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;"
#    - psql -U postgres -c "CREATE DATABASE sqlcmd_test OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;"

#    - psql -U postgres -c "GRANT ALL ON DATABASE sqlcmd TO sqlcmd;"
#    - psql -U postgres -c "GRANT ALL ON DATABASE testdatabase TO sqlcmd;"
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" sqlcmd -U postgres
#    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d sqlcmd -U postgres
#    - psql -U postgres -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d sqlcmd
#    - psql -U postgres -c "GRANT ALL ON SCHEMA public TO sqlcmd;" -d sqlcmd
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" -d sqlcmd_test -U postgres
#    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d sqlcmd_test -U postgres
#    - psql -U postgres -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d sqlcmd_test
#    - psql -U postgres -c "GRANT ALL ON SCHEMA public TO sqlcmd;" -d sqlcmd_test
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE sqlcmd TO public;" -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE testdatabase TO public;" -U postgres
#    - psql -U sqlcmd -c "CREATE TABLE table1 (title varchar(40) NOT NULL);" -d sqlcmd
#    - psql -U sqlcmd -c "CREATE TABLE table1 (title varchar(40) NOT NULL);" -d testdatabase
#    - psql -U postgres -c "select * from pg_namespace;"
#    - psql -U postgres -c "SELECT datname FROM pg_database WHERE datistemplate = false;"
#    - psql -U sqlcmd -c "select * from pg_stat_user_tables;" -d sqlcmd -p 'sqlcmd'
#    - psql -U sqlcmd -c "select * from pg_stat_user_tables;" -d sqlcmd_test -p 'sqlcmd'
#    - psql -U sqlcmd -c " DROP DATABASE testdatabase;" -d sqlcmd

