language: java

services: postgres


before_script:
    - psql -c "CREATE DATABASE sqlcmd;" -U postgres
    - psql -c "CREATE DATABASE testdatabase;" -U postgres
    - psql -c "CREATE USER sqlcmd WITH PASSWORD 'sqlcmd';" -U postgres
