language: java
sudo: required
jdk:
- oraclejdk8

addons:
  postgresql: "9.5"

services:
  - postgresql
before_script:
#    - sudo vim /etc/postgresql/9.5/main/pg_hba.conf
    - psql -U postgres -c "CREATE USER sqlcmd PASSWORD 'sqlcmd' CREATEDB CREATEROLE;"
    - psql -U postgres -c "CREATE DATABASE sqlcmd OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;"
    - psql -U postgres -c "CREATE DATABASE testdatabase OWNER sqlcmd ENCODING = 'UTF8' CONNECTION LIMIT = -1;"
#    - psql -U postgres -c "GRANT ALL ON DATABASE sqlcmd TO sqlcmd;"
#    - psql -U postgres -c "GRANT ALL ON DATABASE testdatabase TO sqlcmd;"
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" sqlcmd -U postgres
#    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d sqlcmd -U postgres
#    - psql -U postgres -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d sqlcmd
#    - psql -U postgres -c "GRANT ALL ON SCHEMA public TO sqlcmd;" -d sqlcmd
#    - psql -c "DROP SCHEMA IF EXISTS public CASCADE;" -d testdatabase -U postgres
#    - psql -c "CREATE SCHEMA public AUTHORIZATION sqlcmd;" -d testdatabase -U postgres
#    - psql -U postgres -c "ALTER SCHEMA public OWNER TO sqlcmd;" -d testdatabase
#    - psql -U postgres -c "GRANT ALL ON SCHEMA public TO sqlcmd;" -d testdatabase
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE sqlcmd TO public;" -U postgres
#    - psql -c "GRANT CONNECT, TEMPORARY ON DATABASE testdatabase TO public;" -U postgres
#    - psql -U sqlcmd -c "CREATE TABLE table1 (title varchar(40) NOT NULL);" -d sqlcmd
#    - psql -U sqlcmd -c "CREATE TABLE table1 (title varchar(40) NOT NULL);" -d testdatabase
#    - psql -U postgres -c "select * from pg_namespace;"
#    - psql -U postgres -c "SELECT datname FROM pg_database WHERE datistemplate = false;"
#    - psql -U sqlcmd -c "select * from pg_stat_user_tables;" -d sqlcmd
#    - psql -U sqlcmd -c "select * from pg_stat_user_tables;" -d testdatabase
#    - psql -U sqlcmd -c " DROP DATABASE testdatabase;" -d sqlcmd

cache:
 directories:
   - $HOME/.m2
   - $HOME/.gradle/caches/
   - $HOME/.gradle/wrapper/
